# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Store-Language
version:      0.01
version_from: lib/Email/Store/Language.pm
installdirs:  site
requires:
    Email::Store:                  0
    Lingua::Identify:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
